<div id="menu"> <!-- meenu bar at the top, of each page.   -->
	<!-- <button type="button" onclick="location.href='splash_sample.php'">Home</button> -->
	<button type="button" onclick="location.href='search.php'">Search</button>
	<button type="button" onclick="location.href='submission.php'">Submission</button>
	<button type="button" onclick="location.href='registration.php'">Registration</button>
	<button type="button" onclick="location.href='login.php'">Login</button>
</div>

<!-- the include for the top of each aoge in php-->